
// all the native method names
export const SHOW_DIALOG = 'showDialog'
export const SHOW_TOAST = 'showToast'
export const GET_LOCATION = 'getLocation'
export const SHOW_PIC = 'showImage'
export const START_APP = 'startApp'
export const SHOW_ATTACHMENT = 'showAttachment'
export const CALL_PHONE = 'callPhone'
export const SEND_MESSAGE = 'sendMessage'
export const GET_NETWORK_TYPE = 'getNetworkType'
export const SELECT_PIC = 'selectPic'
export const SELECT_ATTACHMENT = 'selectAttachment'
export const SELECT_USER = 'selectUser'
export const SELECT_DEPT = 'selectDept'
export const SET_TITLE = 'setTitle'
export const SET_RIGHT = 'setRight'
export const SET_LEFT = 'setLeft'
export const ACTION_SHEET = 'actionSheet'
export const CLOSE_WEBVIEW = 'closeWebview'
export const CHECK_IN = 'checkIn'
export const GET_MAC_ADDRESS = 'getMacAddress'
export const GET_LOCATION_BY_MAP = 'getLocationByMap'
